name: Bug Report
description: "Something is broken with my nodes pack"
labels: ["Potential Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a **Bug Report**, please ensure the following:

        - **1:** You are running the latest version of ComfyUI
        - **2:** You have update my custom-nodes on ComfyUI
      
  - type: textarea
    attributes:
      label: Expected Behavior
      description: "What you expected to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: "What actually happened. Please include a screenshot of the issue if possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "Describe how to reproduce the issue. Please be sure to attach a workflow JSON or PNG
    validations:
      required: true
  - type: textarea
    attributes:
      label: Debug Logs
      description: "Please copy the output from your terminal logs here."
      render: powershell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: "Any other additional information you think might be helpful."
    validations:
      required: false
