name: User Support
description: "Use this if you need help with something"
labels: [ "User Support" ]
body:
    - type: textarea
      attributes:
            label: Your question
            description: "Post your question here. Please be as detailed as possible."
      validations:
            required: true
    - type: textarea
      attributes:
                label: Other
                description: "Any other additional information you think might be helpful."
      validations:
                required: false
